version: '3.8'

services:
  # Настраиваем базу данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: link_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: *  # установить значения для параметров как в .env файле
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Настраиваем Redis
  redis:
    image: redis:7-alpine
    container_name: link_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  pg_data:
  redis_data: